### PR TITLE
transaction sign input index optional

### LINKED ISSUE #79: Address `index` for transaction signing is optional
**Describe the bug**
Optional address `index` for transaction signing.

**Environment information:**

- OS: Mac OS X
- Platform: Darwin 17.4.0 x86_64
- Firmware Version: skycoin/hardware-wallet@46ef0d346a835263d0c060d074652698954613f7
- Service Version: b3232559c589938b7ad39bc67722f2c8a84aa1b8

**Steps to Reproduce**

1. Follow pre-release testing steps up to the point when `TXN4_JSON` is about to be signed
2. Run signing with Skywallet

**Actual behavior**

```sh
$ curl http://127.0.0.1:9510/api/v1/transaction_sign -H 'Content-Type: application/json' -d '{transaction_inputs": [{"hash": "16bae2c5a34510d687165b472e795cee8670a2ff4b4558ab937a64a0f5606ef3", "index": 1}, {"hash": "7dc1f92ec7f92a837bb7055a71061da97861723e38b529dc4b514b312a2a7dd9", "index": 0}, {"hash": "80522a35b6f0f82ae7cb332f91a77c0cadce6675d89fc90eae1939d03bb80100", "index": null }], "transaction_outputs": [{"address": "27Nekv1SdcHuF2q21WnZhXFte25sETeiDC3", "address_index": 2, "coins": "50", "hours": "288868"}]}'
{
    "error": {
        "message": "input index cannot be empty",
        "code": 400
    }
}
```

**Expected behavior**
HTTP 200 and signatures returned in response JSON body.

**Additional context**
The signing can still be performed by including other address index and discarding signature afterwards.

**Possible implementation**
Relax constraint. Allow for specifying `null` values , or just omit it .

### PR DESCRIPTION
**Pull request by therealssj**
Fixes #79 

Changes:
- Remove input index check from transaction sign

Does this change need to mentioned in CHANGELOG.md?
no

Requires changes in protobuff specs?
no
related to PR skycoin/hardware-wallet-protob# for issue skycoin/hardware-wallet-protob#

Requires testing
yes

### CODE REVIEW

File: src/api/transaction_sign_test.go [hunk 1]
```diff
@@ -221,18 +209,41 @@ func TestSignTransaction(t *testing.T) {
...
+				TransactionOutputs: []TransactionOutput{
+					{Address: "2M9hQ4LqEsBF5JZ3uBatnkaMgg9pN965JvG", Coins: "2", Hours: "2"},
+					{Address: "2iNNt6fm9LszSWe51693BeyNUKX34pPaLx8", Coins: "3", Hours: "3"},
+				},
+			}),
+			gatewaySignTransactionResult: wire.Message{
+				Kind: uint16(messages.MessageType_MessageType_Success),
+				Data: successMsgBytes,
+			},
+			httpResponse: HTTPResponse{
```
Comment (olemis) [inline src/api/transaction_sign_test.go]: shouldm't this contain sigs ?
